// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcPod74oDbWFs8AulID64QHpRCLx6qWUU',
    appId: '1:957927708491:web:bd95ae2135f28315efface',
    messagingSenderId: '957927708491',
    projectId: 'memo-fac5e',
    authDomain: 'memo-fac5e.firebaseapp.com',
    storageBucket: 'memo-fac5e.appspot.com',
    measurementId: 'G-3EPWP6ELZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCAjG4TjdeevRasj-0CiZaphcv_omRZyQ',
    appId: '1:957927708491:android:bfec7f4f1351a28eefface',
    messagingSenderId: '957927708491',
    projectId: 'memo-fac5e',
    storageBucket: 'memo-fac5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwHWONB6trXKGtLrdUsuuhtxh12DkwI6A',
    appId: '1:957927708491:ios:711985c0f6124fecefface',
    messagingSenderId: '957927708491',
    projectId: 'memo-fac5e',
    storageBucket: 'memo-fac5e.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwHWONB6trXKGtLrdUsuuhtxh12DkwI6A',
    appId: '1:957927708491:ios:711985c0f6124fecefface',
    messagingSenderId: '957927708491',
    projectId: 'memo-fac5e',
    storageBucket: 'memo-fac5e.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcPod74oDbWFs8AulID64QHpRCLx6qWUU',
    appId: '1:957927708491:web:c9f2332077691eeeefface',
    messagingSenderId: '957927708491',
    projectId: 'memo-fac5e',
    authDomain: 'memo-fac5e.firebaseapp.com',
    storageBucket: 'memo-fac5e.appspot.com',
    measurementId: 'G-R1CTWZXKKY',
  );
}
